

const dummyOffers = [
  { label: 'Housekeeping Services', value: 'housekeeping' },
  { label: 'Deep Cleaning', value: 'deep_cleaning' },
  { label: 'Water Tank Cleaning', value: 'water_tank_cleaning' },
  { label: 'Pest Control', value: 'pest_control' },
  { label: 'Carpet & Sofa Cleaning', value: 'carpet_sofa_cleaning' },
  { label: 'Garden Maintenance', value: 'garden_maintenance' },
  { label: 'Plumbing Services', value: 'plumbing' },
  { label: 'Electrical Repairs', value: 'electrical' },
  { label: 'AC Servicing', value: 'ac_servicing' },
  { label: 'Painting Services', value: 'painting' },
  { label: 'Carpentry Work', value: 'carpentry' },
  { label: 'Security Services', value: 'security' },
  { label: 'Waste Management', value: 'waste_management' },
  { label: 'Elevator Maintenance', value: 'elevator_maintenance' },
  { label: 'Fire Safety Audits', value: 'fire_safety' },
  { label: 'Swimming Pool Cleaning', value: 'pool_cleaning' },
  { label: 'Gym Equipment Repair', value: 'gym_repair' },
  { label: 'Intercom Installation', value: 'intercom' },
  { label: 'CCTV Installation', value: 'cctv' },
  { label: 'Event Management', value: 'event_management' },
  { label: 'Parking Management', value: 'parking_management' },
  { label: 'Lift Attendant', value: 'lift_attendant' },
  { label: 'Courier & Parcel Handling', value: 'courier_handling' },
  { label: 'Visitor Management', value: 'visitor_management' },
  { label: 'Common Area Lighting', value: 'common_area_lighting' },
  { label: 'Drinking Water Supply', value: 'drinking_water_supply' },
  { label: 'Society Office Administration', value: 'office_administration' },
  { label: 'Notice Board Updates', value: 'notice_board_updates' },
  { label: 'Children Play Area Maintenance', value: 'play_area_maintenance' },
  { label: 'Clubhouse Management', value: 'clubhouse_management' },
];

export default dummyOffers;