const dummyData = [
  { 
    id: 1, 
    name: 'Green Wood Society', 
    work: 'Plumbing Work', 
    date: '24th Jun', 
    status: "Completed", 
    postedOn: '2024-06-24', 
    time: '10:00 AM', 
    address: 'Green Wood Society, Tower A, Flat No. 101, Sector 45, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201303', 
    issueDescription: 'Leakage in kitchen sink tap. Society has reported consistent dripping and low water pressure. Inspection and minor repair expected.' 
  },
  { 
    id: 2, 
    name: 'Blue Sky Apartments', 
    work: 'Electrical Repair', 
    date: '25th Jun', 
    status: "Ongoing", 
    postedOn: '2024-06-25', 
    time: '11:00 AM', 
    address: 'Blue Sky Apartments, Tower C, Flat No. 502, Sector 62, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201309', 
    issueDescription: 'Power outage in block B affecting multiple flats. Residents have experienced intermittent supply since last night. Urgent diagnosis and restoration required.' 
  },
  { 
    id: 3, 
    name: 'Red Brick Homes', 
    work: 'Painting Service', 
    date: '26th Jun', 
    status: "Applied", 
    postedOn: '2024-06-26', 
    time: '09:30 AM', 
    address: 'Red Brick Homes, Block D, Flat No. 305, Sector 77, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201304', 
    issueDescription: 'Peeling paint in lobby area. The affected section covers both walls and ceiling. Requesting repainting and surface treatment to prevent recurrence.' 
  },
  { 
    id: 4, 
    name: 'Yellow Stone Co.', 
    work: 'Roofing Inspection', 
    date: '27th Jun', 
    status: "New", 
    postedOn: '2024-06-27', 
    time: '02:00 PM', 
    address: 'Yellow Stone Co., Tower B, Flat No. 1202, Sector 50, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201301', 
    issueDescription: 'Suspected roof leakage after recent rains. Water stains visible on top floor ceilings. Full inspection and report needed before monsoon.' 
  },
  { 
    id: 5, 
    name: 'Purple Haze Estates', 
    work: 'HVAC Maintenance', 
    date: '28th Jun', 
    status: "Ongoing", 
    postedOn: '2024-06-28', 
    time: '03:00 PM', 
    address: 'Purple Haze Estates, Tower D, Flat No. 808, Sector 61, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201307', 
    issueDescription: 'AC not cooling properly in common areas. Residents have complained about rising temperatures. Requesting filter cleaning and gas refill if necessary.' 
  },
  { 
    id: 6, 
    name: 'Orange Blossom Villa', 
    work: 'Garden Landscaping', 
    date: '29th Jun', 
    status: "Completed", 
    postedOn: '2024-06-29', 
    time: '08:00 AM', 
    address: 'Orange Blossom Villa, Villa No. 12, Sector 93A, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201304', 
    issueDescription: 'Overgrown bushes and weeds in garden. Society requests trimming, removal of dead plants, and fresh landscaping for the upcoming festival.' 
  },
  { 
    id: 7, 
    name: 'Silver Stream Towers', 
    work: 'Window Cleaning', 
    date: '30th Jun', 
    status: "Applied", 
    postedOn: '2024-06-30', 
    time: '01:00 PM', 
    address: 'Silver Stream Towers, Tower E, Flat No. 1503, Sector 137, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201305', 
    issueDescription: 'Dirty windows on 5th floor. Residents have reported reduced sunlight and visibility. Deep cleaning required for all exterior glass panels.' 
  },
  { 
    id: 8, 
    name: 'Golden Gate Complex', 
    work: 'Pest Control', 
    date: '1st Jul', 
    status: "New", 
    postedOn: '2024-07-01', 
    time: '10:30 AM', 
    address: 'Golden Gate Complex, Tower F, Flat No. 210, Sector 76, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201306', 
    issueDescription: 'Ant infestation in kitchen and dining areas. Multiple complaints received from residents. Requesting thorough pest control treatment and follow-up.' 
  },
  { 
    id: 9, 
    name: 'Crystal Lake Residency', 
    work: 'Security System Upgrade', 
    date: '2nd Jul', 
    status: "Completed", 
    postedOn: '2024-07-02', 
    time: '12:00 PM', 
    address: 'Crystal Lake Residency, Tower G, Flat No. 1001, Sector 100, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201303', 
    issueDescription: 'Upgrade CCTV cameras at all entry and exit points. Current system is outdated and has blind spots. Proposal for new high-definition cameras requested.' 
  },
  { 
    id: 10, 
    name: 'Sunrise Meadows', 
    work: 'Swimming Pool Cleaning', 
    date: '3rd Jul', 
    status: "Ongoing", 
    postedOn: '2024-07-03', 
    time: '04:00 PM', 
    address: 'Sunrise Meadows, Tower H, Flat No. 305, Sector 78, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201307', 
    issueDescription: 'Pool water is cloudy and has debris. Residents have raised hygiene concerns. Full cleaning, water treatment, and filter check required.' 
  },
  { 
    id: 11, 
    name: 'Maple Leaf Society', 
    work: 'Lift Maintenance', 
    date: '4th Jul', 
    status: "Applied", 
    postedOn: '2024-07-04', 
    time: '09:00 AM', 
    address: 'Maple Leaf Society, Tower J, Flat No. 1102, Sector 52, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201301', 
    issueDescription: 'Lift stuck between floors during peak hours. Emergency rescue was needed. Complete inspection and preventive maintenance requested.' 
  },
  { 
    id: 12, 
    name: 'Emerald Enclave', 
    work: 'Fire Safety Audit', 
    date: '5th Jul', 
    status: "New", 
    postedOn: '2024-07-05', 
    time: '11:30 AM', 
    address: 'Emerald Enclave, Tower K, Flat No. 604, Sector 44, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201303', 
    issueDescription: 'Annual fire safety check due. Society requires audit of extinguishers, alarms, and evacuation routes. Certification and compliance report needed.' 
  },
  { 
    id: 13, 
    name: 'Cedar Woods', 
    work: 'Carpet Cleaning', 
    date: '6th Jul', 
    status: "Completed", 
    postedOn: '2024-07-06', 
    time: '10:15 AM', 
    address: 'Cedar Woods, Tower L, Flat No. 203, Sector 75, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201307', 
    issueDescription: 'Stains in hallway carpet from recent event. Deep cleaning and deodorizing required to restore appearance and hygiene.' 
  },
  { 
    id: 14, 
    name: 'Lakeview Towers', 
    work: 'Water Tank Cleaning', 
    date: '7th Jul', 
    status: "Ongoing", 
    postedOn: '2024-07-07', 
    time: '02:30 PM', 
    address: 'Lakeview Towers, Tower M, Flat No. 1501, Sector 50, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201301', 
    issueDescription: 'Sediment in water supply noticed by residents. Requesting cleaning and disinfection of all overhead and underground tanks.' 
  },
  { 
    id: 15, 
    name: 'Hilltop Residency', 
    work: 'CCTV Installation', 
    date: '8th Jul', 
    status: "Applied", 
    postedOn: '2024-07-08', 
    time: '03:45 PM', 
    address: 'Hilltop Residency, Tower N, Flat No. 702, Sector 79, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201306', 
    issueDescription: 'Install new cameras at entrance and parking area. Security committee has approved budget for additional surveillance.' 
  },
  { 
    id: 16, 
    name: 'Palm Grove Villas', 
    work: 'Intercom Repair', 
    date: '9th Jul', 
    status: "New", 
    postedOn: '2024-07-09', 
    time: '12:45 PM', 
    address: 'Palm Grove Villas, Villa No. 8, Sector 93B, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201304', 
    issueDescription: 'Intercom not working in block C. Residents unable to communicate with security. Urgent repair and system check required.' 
  },
  { 
    id: 17, 
    name: 'Sunset Boulevard', 
    work: 'Parking Lot Painting', 
    date: '10th Jul', 
    status: "Completed", 
    postedOn: '2024-07-10', 
    time: '08:30 AM', 
    address: 'Sunset Boulevard, Tower P, Flat No. 1205, Sector 107, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201304', 
    issueDescription: 'Faded parking lines causing confusion. Society requests repainting of all parking bays and directional arrows.' 
  },
  { 
    id: 18, 
    name: 'Royal Residency', 
    work: 'Gutter Cleaning', 
    date: '11th Jul', 
    status: "Ongoing", 
    postedOn: '2024-07-11', 
    time: '10:00 AM', 
    address: 'Royal Residency, Tower Q, Flat No. 405, Sector 108, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201304', 
    issueDescription: 'Blocked gutters on terrace leading to water overflow. Cleaning and removal of debris required before next rainfall.' 
  },
  { 
    id: 19, 
    name: 'Magnolia Heights', 
    work: 'Door Lock Replacement', 
    date: '12th Jul', 
    status: "Applied", 
    postedOn: '2024-07-12', 
    time: '01:15 PM', 
    address: 'Magnolia Heights, Tower R, Flat No. 902, Sector 104, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201304', 
    issueDescription: 'Broken lock in flat 12B. Residents unable to secure their home. Immediate replacement and spare keys requested.' 
  },
  { 
    id: 20, 
    name: 'Coral Springs', 
    work: 'Facade Cleaning', 
    date: '13th Jul', 
    status: "New", 
    postedOn: '2024-07-13', 
    time: '11:00 AM', 
    address: 'Coral Springs, Tower S, Flat No. 1107, Sector 143, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201305', 
    issueDescription: 'Dust accumulation on facade affecting building appearance. High-pressure cleaning and surface treatment required.' 
  },
  { 
    id: 21, 
    name: 'Amber Heights', 
    work: 'Lift Repair', 
    date: '14th Jul', 
    status: "Completed", 
    postedOn: '2024-07-14', 
    time: '09:00 AM', 
    address: 'Amber Heights, Tower T, Flat No. 301, Sector 105, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201304', 
    issueDescription: 'Lift not stopping at 3rd floor. Residents have reported inconvenience. Repair and safety check required.' 
  },
  { 
    id: 22, 
    name: 'Opal Residency', 
    work: 'Fire Alarm Testing', 
    date: '15th Jul', 
    status: "Ongoing", 
    postedOn: '2024-07-15', 
    time: '10:30 AM', 
    address: 'Opal Residency, Tower U, Flat No. 1202, Sector 110, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201301', 
    issueDescription: 'Annual fire alarm system testing. Residents to be notified of test schedule. Certification required.' 
  },
  { 
    id: 23, 
    name: 'Sapphire Greens', 
    work: 'Garden Lighting Installation', 
    date: '16th Jul', 
    status: "Applied", 
    postedOn: '2024-07-16', 
    time: '05:00 PM', 
    address: 'Sapphire Greens, Tower V, Flat No. 405, Sector 112, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201304', 
    issueDescription: 'Request for new garden lights along walking path. Proposal for energy-efficient LED fixtures.' 
  },
  { 
    id: 24, 
    name: 'Ruby Residency', 
    work: 'Basement Waterproofing', 
    date: '17th Jul', 
    status: "New", 
    postedOn: '2024-07-17', 
    time: '11:45 AM', 
    address: 'Ruby Residency, Tower W, Flat No. 1101, Sector 113, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201305', 
    issueDescription: 'Water seepage in basement parking. Requesting inspection and waterproofing solution.' 
  },
  { 
    id: 25, 
    name: 'Pearl Towers', 
    work: 'Gym Equipment Maintenance', 
    date: '18th Jul', 
    status: "Completed", 
    postedOn: '2024-07-18', 
    time: '07:30 AM', 
    address: 'Pearl Towers, Tower X, Flat No. 1502, Sector 114, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201306', 
    issueDescription: 'Treadmill and elliptical not working. Requesting urgent repair and maintenance.' 
  },
  { 
    id: 26, 
    name: 'Diamond Enclave', 
    work: 'Clubhouse Painting', 
    date: '19th Jul', 
    status: "Ongoing", 
    postedOn: '2024-07-19', 
    time: '02:00 PM', 
    address: 'Diamond Enclave, Tower Y, Flat No. 203, Sector 115, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201307', 
    issueDescription: 'Clubhouse walls require repainting before society event. Requesting color samples and schedule.' 
  },
  { 
    id: 27, 
    name: 'Jade Gardens', 
    work: 'Children Park Repair', 
    date: '20th Jul', 
    status: "Applied", 
    postedOn: '2024-07-20', 
    time: '04:30 PM', 
    address: 'Jade Gardens, Tower Z, Flat No. 504, Sector 116, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201308', 
    issueDescription: 'Broken swings and slides in children park. Requesting repair and safety inspection.' 
  },
  { 
    id: 28, 
    name: 'Topaz Residency', 
    work: 'Boundary Wall Plastering', 
    date: '21st Jul', 
    status: "New", 
    postedOn: '2024-07-21', 
    time: '09:15 AM', 
    address: 'Topaz Residency, Tower AA, Flat No. 601, Sector 117, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201309', 
    issueDescription: 'Cracks in boundary wall plaster. Requesting repair before monsoon.' 
  },
  { 
    id: 29, 
    name: 'Onyx Heights', 
    work: 'Parking Gate Automation', 
    date: '22nd Jul', 
    status: "Completed", 
    postedOn: '2024-07-22', 
    time: '12:00 PM', 
    address: 'Onyx Heights, Tower BB, Flat No. 1002, Sector 118, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201310', 
    issueDescription: 'Manual parking gate to be automated. Proposal for RFID-based entry system.' 
  },
  { 
    id: 30, 
    name: 'Quartz Villas', 
    work: 'Solar Panel Cleaning', 
    date: '23rd Jul', 
    status: "Ongoing", 
    postedOn: '2024-07-23', 
    time: '10:00 AM', 
    address: 'Quartz Villas, Villa No. 15, Sector 119, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201311', 
    issueDescription: 'Dust accumulation on solar panels reducing efficiency. Requesting cleaning and performance check.' 
  },
  { 
    id: 31, 
    name: 'Turquoise Towers', 
    work: 'Lobby AC Repair', 
    date: '24th Jul', 
    status: "Applied", 
    postedOn: '2024-07-24', 
    time: '03:00 PM', 
    address: 'Turquoise Towers, Tower CC, Flat No. 305, Sector 120, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201312', 
    issueDescription: 'Lobby AC not cooling. Residents have complained of discomfort. Requesting urgent repair.' 
  },
  { 
    id: 32, 
    name: 'Ivory Residency', 
    work: 'Sewage Line Cleaning', 
    date: '25th Jul', 
    status: "New", 
    postedOn: '2024-07-25', 
    time: '08:30 AM', 
    address: 'Ivory Residency, Tower DD, Flat No. 1104, Sector 121, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201313', 
    issueDescription: 'Foul smell in basement. Suspected sewage line blockage. Requesting cleaning and inspection.' 
  },
  { 
    id: 33, 
    name: 'Marigold Enclave', 
    work: 'Rainwater Harvesting Maintenance', 
    date: '26th Jul', 
    status: "Completed", 
    postedOn: '2024-07-26', 
    time: '11:00 AM', 
    address: 'Marigold Enclave, Tower EE, Flat No. 1201, Sector 122, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201314', 
    issueDescription: 'Annual maintenance of rainwater harvesting system. Cleaning and filter replacement required.' 
  },
  { 
    id: 34, 
    name: 'Lavender Towers', 
    work: 'Society Notice Board Installation', 
    date: '27th Jul', 
    status: "Ongoing", 
    postedOn: '2024-07-27', 
    time: '01:30 PM', 
    address: 'Lavender Towers, Tower FF, Flat No. 1402, Sector 123, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201315', 
    issueDescription: 'Request for new digital notice board in lobby. Proposal for installation and software integration.' 
  },
  { 
    id: 35, 
    name: 'Willow Woods', 
    work: 'Main Gate Painting', 
    date: '28th Jul', 
    status: "Applied", 
    postedOn: '2024-07-28', 
    time: '02:45 PM', 
    address: 'Willow Woods, Tower GG, Flat No. 1303, Sector 124, Noida, Gautam Buddh Nagar, Uttar Pradesh - 201316', 
    issueDescription: 'Main gate paint peeling off. Requesting repainting and rust treatment.' 
  },
];



export default dummyData;